Logistic regression

Classification
i) Binary classification
Only 2
Sigmoid is used
s=1/1+e^-x
s=1/1+e^-y_predict

ii) Multiple classification
More than 2
Softmax is used

Logistic regression can be used both as multiple an binary classification

Data-> Linear Regression-> Continous output-> sigmoid function-> Output is either 0 or 1
                                          \|/
                                        Softmax function

In [2]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [3]:
iris=load_iris()


In [4]:
x=iris.data
print(x)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [5]:
y=iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
(iris.target_names)

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
#Scaling is only done in x, never y
from sklearn.preprocessing import MinMaxScaler
scale=MinMaxScaler()
x_scaled=scale.fit_transform(x)

In [8]:
# model=LogisticRegression
#model.fit()

In [9]:
x_train, x_test, y_train, y_test=train_test_split(x_scaled, y, test_size=0.3, random_state=10, shuffle=True)

In [10]:
x_train

array([[0.25      , 0.875     , 0.08474576, 0.        ],
       [0.72222222, 0.45833333, 0.66101695, 0.58333333],
       [0.44444444, 0.5       , 0.6440678 , 0.70833333],
       [0.36111111, 0.33333333, 0.66101695, 0.79166667],
       [0.66666667, 0.54166667, 0.79661017, 1.        ],
       [0.52777778, 0.08333333, 0.59322034, 0.58333333],
       [0.80555556, 0.66666667, 0.86440678, 1.        ],
       [0.33333333, 0.16666667, 0.45762712, 0.375     ],
       [0.47222222, 0.375     , 0.59322034, 0.58333333],
       [0.58333333, 0.5       , 0.59322034, 0.58333333],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.27777778, 0.70833333, 0.08474576, 0.04166667],
       [0.5       , 0.375     , 0.62711864, 0.54166667],
       [0.30555556, 0.58333333, 0.11864407, 0.04166667],
       [0.58333333, 0.45833333, 0.76271186, 0.70833333],
       [0.11111111, 0.5       , 0.10169492, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.16666667, 0.20833333,

In [11]:
x_test

array([[0.55555556, 0.125     , 0.57627119, 0.5       ],
       [0.58333333, 0.29166667, 0.72881356, 0.75      ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.5       , 0.41666667, 0.61016949, 0.54166667],
       [0.19444444, 0.54166667, 0.06779661, 0.04166667],
       [0.19444444, 0.        , 0.42372881, 0.375     ],
       [0.55555556, 0.20833333, 0.66101695, 0.58333333],
       [0.41666667, 0.29166667, 0.52542373, 0.375     ],
       [0.22222222, 0.58333333, 0.08474576, 0.04166667],
       [0.38888889, 0.33333333, 0.59322034, 0.5       ],
       [0.36111111, 0.41666667, 0.59322034, 0.58333333],
       [0.41666667, 0.29166667, 0.69491525, 0.75      ],
       [0.33333333, 0.125     , 0.50847458, 0.5       ],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.22222222, 0.75      , 0.08474576, 0.08333333],
       [0.69444444, 0.41666667, 0.76271186, 0.83333333],
       [0.47222222, 0.58333333, 0.59322034, 0.625     ],
       [0.02777778, 0.41666667,

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
#multiple classification 
model=KNeighborsClassifier(n_neighbors=100)
# model=LogisticRegression()
model.fit(x_train,y_train)

,"n_neighbors n_neighbors: int, default=5Number of neighbors to use by default for :meth:`kneighbors` queries.",100
,"weights weights: {'uniform', 'distance'}, callable or None, default='uniform'Weight function used in prediction. Possible values:- 'uniform' : uniform weights. All points in each neighborhood are weighted equally.- 'distance' : weight points by the inverse of their distance. in this case, closer neighbors of a query point will have a greater influence than neighbors which are further away.- [callable] : a user-defined function which accepts an array of distances, and returns an array of the same shape containing the weights.Refer to the example entitled:ref:`sphx_glr_auto_examples_neighbors_plot_classification.py`showing the impact of the `weights` parameter on the decisionboundary.",'uniform'
,"algorithm algorithm: {'auto', 'ball_tree', 'kd_tree', 'brute'}, default='auto'Algorithm used to compute the nearest neighbors:- 'ball_tree' will use :class:`BallTree`- 'kd_tree' will use :class:`KDTree`- 'brute' will use a brute-force search.- 'auto' will attempt to decide the most appropriate algorithm based on the values passed to :meth:`fit` method.Note: fitting on sparse input will override the setting ofthis parameter, using brute force.",'auto'
,"leaf_size leaf_size: int, default=30Leaf size passed to BallTree or KDTree. This can affect thespeed of the construction and query, as well as the memoryrequired to store the tree. The optimal value depends on thenature of the problem.",30
,"p p: float, default=2Power parameter for the Minkowski metric. When p = 1, this is equivalentto using manhattan_distance (l1), and euclidean_distance (l2) for p = 2.For arbitrary p, minkowski_distance (l_p) is used. This parameter is expectedto be positive.",2
,"metric metric: str or callable, default='minkowski'Metric to use for distance computation. Default is ""minkowski"", whichresults in the standard Euclidean distance when p = 2. See thedocumentation of `scipy.spatial.distance<https://docs.scipy.org/doc/scipy/reference/spatial.distance.html>`_ andthe metrics listed in:class:`~sklearn.metrics.pairwise.distance_metrics` for valid metricvalues.If metric is ""precomputed"", X is assumed to be a distance matrix andmust be square during fit. X may be a :term:`sparse graph`, in whichcase only ""nonzero"" elements may be considered neighbors.If metric is a callable function, it takes two arrays representing 1Dvectors as inputs and must return one value indicating the distancebetween those vectors. This works for Scipy's metrics, but is lessefficient than passing the metric name as a string.",'minkowski'
,"metric_params metric_params: dict, default=NoneAdditional keyword arguments for the metric function.",None
,"n_jobs n_jobs: int, default=NoneThe number of parallel jobs to run for neighbors search.``None`` means 1 unless in a :obj:`joblib.parallel_backend` context.``-1`` means using all processors. See :term:`Glossary <n_jobs>`for more details.Doesn't affect :meth:`fit` method.",None
Name,Type,Value
"classes_ classes_: array of shape (n_classes,)Class labels known to the classifier","ndarray[int64](3,)","[0,1,2]"
"effective_metric_ effective_metric_: str or callbleThe distance metric used. It will be same as the `metric` parameteror a synonym of it, e.g. 'euclidean' if the `metric` parameter set to'minkowski' and `p` parameter set to 2.",str,'eu...an'


In [13]:
x_test

array([[0.55555556, 0.125     , 0.57627119, 0.5       ],
       [0.58333333, 0.29166667, 0.72881356, 0.75      ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.5       , 0.41666667, 0.61016949, 0.54166667],
       [0.19444444, 0.54166667, 0.06779661, 0.04166667],
       [0.19444444, 0.        , 0.42372881, 0.375     ],
       [0.55555556, 0.20833333, 0.66101695, 0.58333333],
       [0.41666667, 0.29166667, 0.52542373, 0.375     ],
       [0.22222222, 0.58333333, 0.08474576, 0.04166667],
       [0.38888889, 0.33333333, 0.59322034, 0.5       ],
       [0.36111111, 0.41666667, 0.59322034, 0.58333333],
       [0.41666667, 0.29166667, 0.69491525, 0.75      ],
       [0.33333333, 0.125     , 0.50847458, 0.5       ],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.22222222, 0.75      , 0.08474576, 0.08333333],
       [0.69444444, 0.41666667, 0.76271186, 0.83333333],
       [0.47222222, 0.58333333, 0.59322034, 0.625     ],
       [0.02777778, 0.41666667,

In [14]:
y_test

array([1, 2, 0, 1, 0, 1, 1, 1, 0, 1, 1, 2, 1, 0, 0, 2, 1, 0, 0, 0, 2, 2,
       2, 0, 1, 0, 1, 1, 1, 2, 1, 1, 2, 2, 2, 0, 2, 2, 2, 2, 0, 0, 1, 0,
       1])

In [15]:
import numpy as np
test=np.array([[0.677,0.21333, 0.5433, 0.822]])
test_scaled=scale.fit_transform(test)
test_scaled

array([[0., 0., 0., 0.]])

In [16]:
y_pred=model.predict(x_test)

In [17]:
y_pred

array([2, 2, 0, 2, 0, 0, 2, 2, 0, 2, 2, 2, 2, 0, 0, 2, 2, 0, 0, 0, 2, 2,
       2, 0, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 0, 2, 0,
       2])

In [18]:
y_prob=model.predict_proba(test)
y_prob

array([[0.31, 0.33, 0.36]])

In [19]:
y_prob

array([[0.31, 0.33, 0.36]])

In [20]:
from sklearn.metrics import classification_report,accuracy_score
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.93      1.00      0.97        14
           1       0.00      0.00      0.00        17
           2       0.47      1.00      0.64        14

    accuracy                           0.62        45
   macro avg       0.47      0.67      0.53        45
weighted avg       0.44      0.62      0.50        45

0.6222222222222222


c:\Users\Resham\Desktop\WIA\CLASS\library\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Resham\Desktop\WIA\CLASS\library\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Resham\Desktop\WIA\CLASS\library\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{me