1. Create a 1D NumPy array containing the numbers from 10 to 50 (inclusive) with a step of
5.
● Print the entire array.
● Access and print the 3rd element.
● Access and print the last element using negative indexing.




In [2]:
import numpy as np

In [3]:
a=np.arange(10,55,5)
a

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [7]:
a[2]


np.int64(20)

In [5]:
a[-1]

np.int64(50)

2. Create a 2D NumPy array of shape (3, 4) filled with numbers from 1 to 12 (row-wise).
● Print the entire array.
● Access and print the element at row 1, column 2.

In [19]:
a1=np.arange(1,13)#->range jstai 
d2=a1.reshape(3,4)
d2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
d2[1][2]

np.int64(7)

3. Create a 3D NumPy array of shape (2, 3, 4) filled with sequential numbers starting from
1.
● Print the entire array.
● Access and print the element at depth 0, row 1, column 2.

In [3]:
#->3d
d3=np.arange(24).reshape(2,3,4)
d3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [4]:
d3[0,1,2]

np.int64(6)

4. Calculate mean median Variance, Standard deviation of
a. 12,32,56,32,87,65,45,32,12,32
b. 34,56,87,98,12,43,21,45,67,87,22,43

In [5]:
m1= [12,32,56,32,87,65,45,32,12,32]
m2=[34,56,87,98,12,43,21,45,67,87,22,43]
m=np.array(m1)
m

array([12, 32, 56, 32, 87, 65, 45, 32, 12, 32])

In [7]:
n=np.array(m2)
n

array([34, 56, 87, 98, 12, 43, 21, 45, 67, 87, 22, 43])

In [9]:
np.mean(m)


np.float64(40.5)

In [10]:
np.mean(n)

np.float64(51.25)

In [11]:
np.median(n)

np.float64(44.0)

In [13]:
np.median(m)

np.float64(32.0)

In [14]:
np.var(m)

np.float64(493.65)

In [15]:
np.var(n)

np.float64(733.0208333333334)

In [16]:
np.std(m)

np.float64(22.21823575354263)

In [17]:
np.std(m)

np.float64(22.21823575354263)