In [2]:
import numpy as np 

In [3]:
a=np.array
a=np.array([1,2,3,4,5,6,7,8])
print(a)


[1 2 3 4 5 6 7 8]


In [4]:
a[0:5]

array([1, 2, 3, 4, 5])

In [6]:
a[-4:-1]

array([5, 6, 7])

In [8]:
#2d array
a=np.arange(24).reshape(4,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [9]:
a[0]

array([0, 1, 2, 3, 4, 5])

In [10]:
a[0,-3:]

array([3, 4, 5])

start:end:strip

In [11]:
a[0:5:2,1:4:2]

array([[ 1,  3],
       [13, 15]])

In [16]:
a[0:4:3,0:6:5]

array([[ 0,  5],
       [18, 23]])

array([], shape=(2, 0), dtype=int64)

In [ ]:
#3d
b=np.arange(60).reshape(3,4,-1)  #-1 automatically assign 5 
b

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

#->flatteing

In [ ]:
b.reshape(-1)#->1d array ma jnxa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [25]:
b[1,2,:]

array([30, 31, 32, 33, 34])

In [33]:
b[1,0:5:2,1:4:2]

array([[21, 23],
       [31, 33]])

In [ ]:
b[[1,2],[3,0],:]    #->xuta xutai block ma 

array([[35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44]])

In [35]:
f=np.arange(12).reshape(3,4)

In [36]:
f

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
np.mean(f)

np.float64(5.5)

In [39]:
np.mean(f,axis=0)#axis=0 col,1 row

array([4., 5., 6., 7.])

In [41]:
np.median(f)

np.float64(5.5)

In [42]:
np.median(f,axis=1)

array([1.5, 5.5, 9.5])

In [44]:
np.var(f,axis=1)

array([1.25, 1.25, 1.25])

In [45]:
np.std(a)

np.float64(6.922186552431729)